--- 
driver: 
  name: docker
  use_sudo: false

provisioner:
  name: chef_solo

driver_config: 
  privileged: true
  provision_command: "yum install net-tools lsof initscripts -y"
  require_chef_omnibus: "12.16.42"
  run_command: /usr/sbin/init

platforms: 
  - name: centos-7.2

suites: 
  - name: default
    run_list:
      - "recipe[selenium-liatrio::default]"
    attributes: 
      selenium_liatrio:
        user: "kitchen"
        group: "kitchen"
        home: "/home/kitchen"
      java: 
        jdk_version: "8"
