---
driver:
  name: docker
  use_sudo: true
  run_command: yum install initscripts

platforms:
  - name: centos-7.2

suites:
  - name: default
    run_list:
      - recipe[selenium-liatrio::default]
    attributes:
      java:
        jdk_version: "8"
